config/routes.rb
Rails.application.routes.draw do

  # scaffold routes
  resources :dies
  resources :coins
  resources :users

  # sign in page
  get     'register', to:     'sessions#register'
  post    'sign_in', to:      'sessions#sign_in' 
  post    'sign_up', to:      'sessions#sign_up'

  # user page
  get     'profile', to:      'sessions#profile'
  delete  'sign_out', to:     'sessions#sign_out'
  delete  'delete_user', to:  'sessions#delete_user'

  # game page
  get     'game', to:         'sessions#game'
  post    'turn', to:         'sessions#turn'
  
  # set our root
  root 'sessions#register'
  
end

app/controllers/dies_controller.rb
class DiesController < ApplicationController
  before_action :set_dy, only: %i[ show edit update destroy ]

  # GET /dies or /dies.json
  def index
    @dies = Die.all
  end

  # GET /dies/1 or /dies/1.json
  def show
  end

  # GET /dies/new
  def new
    @dy = Die.new
  end

  # GET /dies/1/edit
  def edit
  end

  # POST /dies or /dies.json
  def create
    @dy = Die.new(dy_params)

    respond_to do |format|
      if @dy.save
        format.html { redirect_to @dy, notice: "Die was successfully created." }
        format.json { render :show, status: :created, location: @dy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dies/1 or /dies/1.json
  def update
    respond_to do |format|
      if @dy.update(dy_params)
        format.html { redirect_to @dy, notice: "Die was successfully updated." }
        format.json { render :show, status: :ok, location: @dy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dies/1 or /dies/1.json
  def destroy
    @dy.destroy
    respond_to do |format|
      format.html { redirect_to dies_url, notice: "Die was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dy
      @dy = Die.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dy_params
      params.require(:dy).permit(:fk_user_id, :colour, :sides)
    end
end

app/helpers/dies_helper.rb
module DiesHelper
end

app/views/dies/_form.html.erb
<%= form_with(model: dy, local: true) do |form| %>
  <% if dy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dy.errors.count, "error") %> prohibited this dy from being saved:</h2>

      <ul>
        <% dy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fk_user_id %>
    <%= form.number_field :fk_user_id %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :sides %>
    <%= form.number_field :sides %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dies/edit.html.erb
<h1>Editing Dy</h1>

<%= render 'form', dy: @dy %>

<%= link_to 'Show', @dy %> |
<%= link_to 'Back', dies_path %>

app/views/dies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dies</h1>

<table>
  <thead>
    <tr>
      <th>Fk user</th>
      <th>Colour</th>
      <th>Sides</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dies.each do |dy| %>
      <tr>
        <td><%= dy.fk_user_id %></td>
        <td><%= dy.colour %></td>
        <td><%= dy.sides %></td>
        <td><%= link_to 'Show', dy %></td>
        <td><%= link_to 'Edit', edit_dy_path(dy) %></td>
        <td><%= link_to 'Destroy', dy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dy', new_dy_path %>

app/views/dies/new.html.erb
<h1>New Dy</h1>

<%= render 'form', dy: @dy %>

<%= link_to 'Back', dies_path %>

app/views/dies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fk user:</strong>
  <%= @dy.fk_user_id %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @dy.colour %>
</p>

<p>
  <strong>Sides:</strong>
  <%= @dy.sides %>
</p>

<%= link_to 'Edit', edit_dy_path(@dy) %> |
<%= link_to 'Back', dies_path %>